services:

  postgres:
    image: postgres:18
    container_name: nexus_pg_db
    restart: always
    environment:
      POSTGRES_DB: ${NEXUS_DB_NAME:?error}
      POSTGRES_USER: ${NEXUS_DB_USER:?error}
      POSTGRES_PASSWORD: ${NEXUS_DB_PWD:?error}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
        - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?error}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD:?eroor}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 86400 # 一天 
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 7200    # 一小時登出
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pg_data:
  pgadmin_data: