services:
  postgres:
    image: postgres:18
    container_name: nexus_pg_db
    restart: always
    environment:
      POSTGRES_DB: ${NEXUS_DB_NAME:?error}
      POSTGRES_USER: ${NEXUS_DB_USER:?error}
      POSTGRES_PASSWORD: ${NEXUS_DB_PWD:?error}
      PGDATA: /var/lib/postgresql/data
    command: >
      postgres
        -c shared_buffers=128MB
        -c max_connections=20
        -c work_mem=8MB
        -c maintenance_work_mem=32MB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  redis:
    image: redis:8-alpine
    container_name: nexus_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
        --protected-mode yes
        --requirepass ${REDIS_PASSWORD:?error}
        --appendonly yes
        --appendfsync everysec
        --maxmemory 128mb
        --maxmemory-policy allkeys-lru
        --bind 0.0.0.0
        --save 900 1
        --save 300 10
        --save 60 10000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?error}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD:?error}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 86400 # 一天
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 7200 # 一小時登出
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api-image
    container_name: testapi
    ports:
      - "8000:8000"
    environment:
      - NEXUS_DB_HOST=nexus_pg_db
      - NEXUS_DB_PORT=5432
      - REDIS_LOCATION=redis://nexus_redis:6379/1
    depends_on:
      - postgres
      - redis

volumes:
  pg_data:
  redis_data:
    name: nexus_redis_data
  pgadmin_data:
